# Generated by Django 2.2.2 on 2019-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_greeting_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeting',
            name='id',
        ),
        migrations.AlterField(
            model_name='greeting',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
