# Generated by Django 2.2.2 on 2019-06-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20190621_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greeting',
            new_name='bank_details',
        ),
        migrations.AlterModelTable(
            name='bank_details',
            table='bank_details',
        ),
    ]
